#!/usr/bin/env python3
#
# Draws the social preview card - the picture GitHub shows when the repository
# is linked anywhere with a link preview, and the one thing about this project
# most people will see before they see the project.
#
# Written out rather than mocked up for the same reason the icon is: a card that
# comes out of a script can be argued with, and it stays on the palette the app
# actually uses instead of drifting to whatever was open in an image editor.
#
# 1280x640 is what GitHub asks for. It is shown at half that in a feed and
# cropped tighter still by some clients, so everything that has to be legible
# sits inside a generous margin and nothing depends on the edges.
#
# The icon is embedded rather than redrawn: it is already generated by
# scripts/make-icon.py, and two copies of the same geometry is one too many.
#
# Usage: npm run build:social

import base64
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICON = ROOT / "src-tauri/icons/icon.png"
OUT_SVG = ROOT / "assets/social-preview.svg"
OUT_PNG = ROOT / "assets/social-preview.png"

W, H = 1280, 640

# The dark theme's own tokens, from src/routes/+layout.svelte, and the two
# gradients the icon is built from. Kept as literals because this script draws a
# picture rather than a page: there is no CSS here to inherit them from.
BG = "#101216"
TEXT = "#edeff3"
MUTED = "#99a1af"
DIM = "#666e7c"

# Mark and text are one block, centred on the canvas rather than hung off the
# left edge: the card is cropped to several different shapes by the places that
# show it, and a group in the middle survives all of them.
ICON_SIZE = 268
ICON_X = 220
TEXT_X = 564

# The text is taller than the mark, so its baselines are set from a common
# optical centre rather than from the top - otherwise the block reads as sitting
# lower than the thing beside it.
BASELINES = {
    "name": 221,
    "line1": 293,
    "line2": 345,
    "rule": 379,
    "offline": 433,
    "built": 489,
}


def card(icon_data_uri: str) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 {W} {H}" width="{W}" height="{H}">
  <defs>
    <!-- The page is one flat colour; the light comes from behind the mark, the
         way it does in the app's own level indicator. -->
    <radialGradient id="glow" cx="0.28" cy="0.5" r="0.62">
      <stop offset="0" stop-color="#2b3550" stop-opacity="0.85"/>
      <stop offset="0.55" stop-color="#171d2b" stop-opacity="0.5"/>
      <stop offset="1" stop-color="{BG}" stop-opacity="0"/>
    </radialGradient>

    <!-- The same sweep that runs across the icon's waves, reused on the one
         line of text that is the whole pitch. -->
    <linearGradient id="aurora" x1="0" y1="0" x2="1" y2="0.6">
      <stop offset="0" stop-color="#2ee6d4"/>
      <stop offset="0.4" stop-color="#38aaff"/>
      <stop offset="1" stop-color="#7b6bff"/>
    </linearGradient>

    <!-- A hairline under the mark, so the card has a horizon rather than a
         floating pair of objects. -->
    <linearGradient id="rule" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#2ee6d4" stop-opacity="0.55"/>
      <stop offset="0.5" stop-color="#7b6bff" stop-opacity="0.3"/>
      <stop offset="1" stop-color="#7b6bff" stop-opacity="0"/>
    </linearGradient>
  </defs>

  <rect width="{W}" height="{H}" fill="{BG}"/>
  <rect width="{W}" height="{H}" fill="url(#glow)"/>

  <image x="{ICON_X}" y="{(H - ICON_SIZE) // 2}"
         width="{ICON_SIZE}" height="{ICON_SIZE}"
         xlink:href="{icon_data_uri}"/>

  <g font-family="-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', Arial, sans-serif">
    <text x="{TEXT_X}" y="{BASELINES['name']}" fill="{TEXT}" font-size="104" font-weight="600"
          letter-spacing="-3">Marswind</text>

    <text x="{TEXT_X}" y="{BASELINES['line1']}" fill="{MUTED}" font-size="41" font-weight="400">Live subtitles and translation</text>
    <text x="{TEXT_X}" y="{BASELINES['line2']}" fill="{MUTED}" font-size="41" font-weight="400">for your computer's audio</text>

    <rect x="{TEXT_X}" y="{BASELINES['rule']}" width="360" height="1.5" fill="url(#rule)"/>

    <text x="{TEXT_X}" y="{BASELINES['offline']}" fill="url(#aurora)" font-size="41" font-weight="600">Fully offline</text>

    <text x="{TEXT_X}" y="{BASELINES['built']}" fill="{DIM}" font-size="25" font-weight="400"
          letter-spacing="0.4">macOS · whisper.cpp · llama.cpp · Rust · MIT</text>
  </g>
</svg>
"""


def main():
    if not ICON.is_file():
        sys.exit(f"no icon at {ICON} - run `npm run build:icons` first")

    data_uri = "data:image/png;base64," + base64.b64encode(ICON.read_bytes()).decode()
    OUT_SVG.write_text(card(data_uri))
    print(f"==> {OUT_SVG.relative_to(ROOT)}")

    # Same rasterizer as the icon, for the same reason: there is none in the
    # standard toolchain, and Chrome renders SVG the way the app's own webview
    # would.
    chrome = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    if not pathlib.Path(chrome).is_file():
        sys.exit(
            f"no rasterizer at '{chrome}'.\n"
            f"       convert {OUT_SVG.relative_to(ROOT)} to a {W}x{H} PNG yourself."
        )

    subprocess.run(
        [
            chrome,
            "--headless",
            "--disable-gpu",
            f"--screenshot={OUT_PNG}",
            f"--window-size={W},{H}",
            "--default-background-color=00000000",
            "--hide-scrollbars",
            f"file://{OUT_SVG}",
        ],
        capture_output=True,
        check=True,
    )
    print(f"==> {OUT_PNG.relative_to(ROOT)}  ({OUT_PNG.stat().st_size // 1024} KB)")
    print()
    print("Upload it by hand: Settings → General → Social preview → Edit.")
    print("There is no API for this one.")


if __name__ == "__main__":
    main()
